-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE (
    SELECT DISTINCT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE ITEM_TREE.PARENT_ITEM_ID = ITEM_INFO.ITEM_ID
) IS NULL
ORDER BY ITEM_ID DESC;
