-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO A
WHERE A.FAVORITES = (
    SELECT MAX(B.FAVORITES)
    FROM REST_INFO B
    WHERE B.FOOD_TYPE = A.FOOD_TYPE
)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;