

-- 코드를 작성해주세요
SELECT ID, 
(
    CASE 
        WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) = 4 THEN "CRITICAL"
        WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) = 3 THEN "HIGH"
        WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) = 2 THEN "MEDIUM"
        ELSE "LOW"
    END
)
AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;