-- 코드를 입력하세요
# SELECT CAR_ID, "대여 가능" IN AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY


SELECT CAR_ID, "대여중" AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= "2022-10-16" AND END_DATE >= "2022-10-16"
GROUP BY CAR_ID

UNION

SELECT CAR_ID, "대여 가능" AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
NOT (START_DATE <= "2022-10-16" AND END_DATE >= "2022-10-16") AND
CAR_ID NOT IN (
    SELECT C.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    WHERE C.START_DATE <= "2022-10-16" AND C.END_DATE >= "2022-10-16"
    GROUP BY C.CAR_ID
)

GROUP BY CAR_ID

ORDER BY CAR_ID DESC;
