-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, SUM(A.PRICE*B.sales_amount) as SALES 
from PRODUCT A
inner JOIN OFFLINE_SALE B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES desc, PRODUCT_CODE asc