-- 코드를 입력하세요
SELECT H.HISTORY_ID,  CAST (C.DAILY_FEE * (100-NVL(P.DISCOUNT_RATE,0)) / 100 * (H.END_DATE - H.START_DATE + 1) AS NUMBER(38)) AS FEE

FROM (
    SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE,
        CASE
            WHEN END_DATE - START_DATE + 1 >= 90 THEN '90일 이상'
            WHEN END_DATE - START_DATE + 1 >= 30 THEN '30일 이상'
            WHEN END_DATE - START_DATE + 1 >= 7 THEN '7일 이상'        
            ELSE ''
        END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    
) H

INNER JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = H.DURATION

WHERE C.CAR_TYPE = '트럭'

ORDER BY FEE DESC, HISTORY_ID DESC;