-- 코드를 작성해주세요
SELECT A.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE A
JOIN ITEM_INFO B
ON A.PARENT_ITEM_ID = B.ITEM_ID
JOIN ITEM_INFO C
ON A.ITEM_ID = C.ITEM_ID
WHERE B.RARITY = "RARE"
ORDER BY A.ITEM_ID DESC;