-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO A
WHERE (
    SELECT C.RARITY
    FROM ITEM_INFO C
    WHERE C.ITEM_ID = (
        SELECT B.PARENT_ITEM_ID
        FROM ITEM_TREE B
        WHERE B.ITEM_ID = A.ITEM_ID
    ) 
) = "RARE"
ORDER BY ITEM_ID DESC;