-- 코드를 작성해주세요
SELECT A.ID, A.GENOTYPE, (
    SELECT C.GENOTYPE
    FROM ECOLI_DATA C
    WHERE C.ID = A.PARENT_ID
) AS PARENT_GENOTYPE
FROM ECOLI_DATA A
WHERE A.GENOTYPE & (
    SELECT B.GENOTYPE
    FROM ECOLI_DATA B
    WHERE B.ID = A.PARENT_ID
) >= (
    SELECT B.GENOTYPE
    FROM ECOLI_DATA B
    WHERE B.ID = A.PARENT_ID
)
ORDER BY ID;