-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31" 
    AND CAR_ID IN (
        SELECT C.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
        WHERE C.START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
        GROUP BY C.CAR_ID
        HAVING COUNT(*) >= 5
    )
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH, CAR_ID DESC;