-- 코드를 입력하세요
SELECT a.FLAVOR 
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
    HAVING SUM(TOTAL_ORDER) >= 3000
) a
JOIN ICECREAM_INFO b
ON a.FLAVOR = b.FLAVOR
WHERE b.INGREDIENT_TYPE = "fruit_based"
ORDER BY a.TOTAL DESC;
    