-- 코드를 작성해주세요
SELECT A.ID, N.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO N
ON A.FISH_TYPE = N.FISH_TYPE
WHERE LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO B
    WHERE A.FISH_TYPE = B.FISH_TYPE
);
