SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
LEFT JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (
    SELECT MAX(C.LENGTH)
    FROM FISH_INFO C
    WHERE C.FISH_TYPE = B.FISH_TYPE
)
ORDER BY A.ID;
