SELECT b.TITLE, b.BOARD_ID, a.REPLY_ID, a.WRITER_ID, a.CONTENTS, DATE_FORMAT(a.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY a
LEFT JOIN USED_GOODS_BOARD b
on a.BOARD_ID = b.BOARD_ID
WHERE 1=1
AND b.CREATED_DATE LIKE "2022-10%"
-- AND a.CREATED_DATE LIKE "2022-10%"
ORDER BY a.CREATED_DATE, TITLE;