-- 코드를 입력하세요
SELECT CONCAT(
    '/home/grep/src/', 
    A.BOARD_ID,
    '/' , 
    A.FILE_ID,
    A.FILE_NAME,
    A.FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE A
WHERE A.BOARD_ID = (
    SELECT B.BOARD_ID
    FROM USED_GOODS_BOARD  B
    ORDER BY VIEWS DESC LIMIT 1
)
ORDER BY FILE_ID DESC;