-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, 
DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') as DATE_OF_BIRTH
from MEMBER_PROFILE
where MID(DATE_OF_BIRTH,7,1) = 3 and TLNO is Not NULL and GENDER = 'W'
order by MEMBER_ID